### ISSUE TITLE
Use tomllib/tomli instead of toml

### ISSUE THREAD

**Issue by jvllmr** [jordantshaw/pydantic-config#16]
With Python 3.11 tomli became a part of the Python Standard Library with the tomli library providing a backport for Python 3.10 and lower (https://peps.python.org/pep-0680/).

I think it would be great to switch to tomli because you could avoid one extra dependency when using Python 3.11 or higher (use a version constraint that drops the dependency if using a specific python version; https://packaging.python.org/en/latest/specifications/dependency-specifiers/#environment-markers).

**Comment by jordantshaw** [comment]
@jvllmr good suggestion.  I will get this added.

**Comment by jordantshaw** [comment]
Included in https://github.com/jordantshaw/pydantic-config/releases/tag/v0.3.0
