### ISSUE TITLE
Support to supply env file

### ISSUE THREAD

**Issue by yli02** [jordantshaw/pydantic-config#19]
Hi @jordantshaw, thanks for your effort in creating this library, it is very useful to me. May I ask whether it is fine to consider adding the support to add env file as well? Thanks.

**Comment by jordantshaw** [comment]
@yli02 dotenv files are actually supported natively by pydantic-settings. So any environment variables loaded via environment file will take precedence over the config file values. I suppose this could be better documented with some examples. I'll add that to the documentation. But it would just look something like this.

```
class Settings(SettingsModel):
  app_name: str = None
  description: str = None
    
    model_config = SettingsConfig(
        env_file='.env',
        config_file='config.toml',
    )
```

**Comment by yli02** [comment]
@jordantshaw thanks, it is clear now to me.
